from __future__ import annotations

from app.exchange_info_base.common import account_type, endpoint, market_type, price_types
from app.exchange_info_base.models import ExchangeReference

BITGET_REFERENCE = ExchangeReference(
    exchange_id="bitget",
    title="Bitget",
    verified_scope="Official Bitget Classic and UTA docs for Spot/Futures market, account and trade routes.",
    account_types=(
        account_type("classic_spot", "Classic Spot", "Классический spot-аккаунт Bitget.", tradable_products=("spot",)),
        account_type("classic_futures", "Classic Futures", "Классический futures-аккаунт Bitget.", tradable_products=("usdt_futures", "coin_futures", "usdc_futures")),
        account_type("uta_spot_mode", "UTA Spot Mode", "UTA Spot Mode — только спот, без margin/futures.", tradable_products=("spot",)),
        account_type("uta_basic_mode", "UTA Basic Mode", "UTA Basic Mode — spot + USDT perpetual + USDC perpetual.", tradable_products=("spot", "usdt_futures", "usdc_futures")),
        account_type("uta_advanced_mode", "UTA Advanced Mode", "UTA Advanced Mode — spot, leverage, USDT perpetual, USDC perpetual, Coin-M.", tradable_products=("spot", "margin", "usdt_futures", "usdc_futures", "coin_futures")),
    ),
    market_types=(
        market_type("spot", "Spot", native_categories=("spot",)),
        market_type("margin", "Margin", native_categories=("margin", "leverage")),
        market_type("usdt_futures", "USDT-FUTURES", native_categories=("USDT-FUTURES",), settlement_types=("USDT",)),
        market_type("coin_futures", "COIN-FUTURES", native_categories=("COIN-FUTURES",), settlement_types=("coin-margined",)),
        market_type("usdc_futures", "USDC-FUTURES", native_categories=("USDC-FUTURES",), settlement_types=("USDC",)),
    ),
    price_types=price_types("last", "bid", "ask", "mid", "mark", "index", "open", "high", "low", "close"),
    endpoints=(
        endpoint("spot_tickers", group="market_data", market="spot", title="Spot Tickers", method="GET", path="/api/v2/spot/market/tickers", auth="public", symbol_mode="bulk_or_symbol", response_symbol_field="data[].symbol", response_fields=("lastPr", "bidPr", "askPr", "usdtVolume"), price_types=("last", "bid", "ask", "mid"), intended_use="Bulk snapshot spot price/bid/ask/volume.", source_urls=("https://www.bitget.com/api-doc/spot/market/Get-Tickers",)),
        endpoint("spot_candles", group="market_data", market="spot", title="Spot Candles", method="GET", path="/api/v2/spot/market/candles", auth="public", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Текущие/недавние spot свечи.", source_urls=("https://www.bitget.com/api-doc/spot/market/Get-Candle-Data",)),
        endpoint("spot_history_candles", group="market_data", market="spot", title="Spot History Candles", method="GET", path="/api/v2/spot/market/history-candles", auth="public", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Исторические spot OHLC.", source_urls=("https://www.bitget.com/api-doc/spot/market/Get-History-Candle-Data",)),
        endpoint("spot_account_assets", group="account", market="spot", title="Spot Account Assets", method="GET", path="/api/v2/spot/account/assets", auth="user_data", symbol_mode="none", response_symbol_field="data[].coin", response_fields=("coin", "available", "frozen", "locked"), price_types=(), intended_use="Spot balances.", source_urls=("https://www.bitget.com/api-doc/spot/account/Get-Account-Assets",)),
        endpoint("spot_order", group="trade", market="spot", title="Spot Place Order", method="POST", path="/api/v2/spot/trade/place-order", auth="trade", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("orderId", "clientOid"), price_types=(), intended_use="Выставление spot-ордера.", source_urls=("https://www.bitget.com/api-doc/spot/trade/Place-Order",)),
        endpoint("futures_all_tickers", group="market_data", market="usdt_futures", title="Futures All Tickers", method="GET", path="/api/v2/mix/market/tickers", auth="public", symbol_mode="product_type", response_symbol_field="data[].symbol", response_fields=("lastPr", "askPr", "bidPr", "usdtVolume", "indexPrice", "fundingRate", "markPrice", "deliveryTime"), price_types=("last", "bid", "ask", "mid", "mark", "index"), intended_use="Bulk snapshot futures prices for one productType.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-All-Symbol-Ticker",)),
        endpoint("futures_contracts", group="market_data", market="usdt_futures", title="Futures Contracts", method="GET", path="/api/v2/mix/market/contracts", auth="public", symbol_mode="product_type", response_symbol_field="data[].symbol", response_fields=("symbol", "symbolStatus", "symbolType", "baseCoin", "quoteCoin", "supportMarginCoins"), price_types=(), intended_use="Universe futures contracts by productType.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-All-Symbols-Contracts",)),
        endpoint("futures_single_ticker", group="market_data", market="usdt_futures", title="Futures Single Ticker", method="GET", path="/api/v2/mix/market/ticker", auth="public", symbol_mode="product_type_and_symbol", response_symbol_field="data[].symbol", response_fields=("lastPr", "askPr", "bidPr", "usdtVolume", "indexPrice", "fundingRate", "markPrice", "deliveryTime"), price_types=("last", "bid", "ask", "mid", "mark", "index"), intended_use="Selective futures ticker by symbol.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-Ticker",)),
        endpoint("futures_current_fund_rate", group="market_data", market="usdt_futures", title="Current Funding Rate", method="GET", path="/api/v2/mix/market/current-fund-rate", auth="public", symbol_mode="product_type", response_symbol_field="data[].symbol", response_fields=("symbol", "fundingRate", "fundingRateInterval", "nextUpdate"), price_types=(), intended_use="Funding snapshot по futures productType.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-Current-Funding-Rate",)),
        endpoint("futures_candles", group="market_data", market="usdt_futures", title="Futures Candles", method="GET", path="/api/v2/mix/market/candles", auth="public", symbol_mode="product_type_and_symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Текущие/недавние futures candles.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-Candle-Data",)),
        endpoint("futures_history_candles", group="market_data", market="usdt_futures", title="Futures History Candles", method="GET", path="/api/v2/mix/market/history-candles", auth="public", symbol_mode="product_type_and_symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Исторические futures OHLC.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-History-Candle-Data",)),
        endpoint("futures_mark_history_candles", group="market_data", market="usdt_futures", title="Futures Historical Mark Candles", method="GET", path="/api/v2/mix/market/history-mark-candles", auth="public", symbol_mode="product_type_and_symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("mark", "close"), intended_use="История mark-price по futures.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-History-Mark-Candle-Data",)),
        endpoint("futures_index_history_candles", group="market_data", market="usdt_futures", title="Futures Historical Index Candles", method="GET", path="/api/v2/mix/market/history-index-candles", auth="public", symbol_mode="product_type_and_symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("index", "close"), intended_use="История index-price по futures.", source_urls=("https://www.bitget.com/api-doc/contract/market/Get-History-Index-Candle-Data",)),
        endpoint("futures_account_single", group="account", market="usdt_futures", title="Futures Get Single Account", method="GET", path="/api/v2/mix/account/account", auth="user_data", symbol_mode="product_type_and_symbol", response_symbol_field="data.marginCoin", response_fields=("marginCoin", "available", "accountEquity", "usdtEquity"), price_types=(), intended_use="Проверка конкретного futures account по productType и marginCoin.", source_urls=("https://www.bitget.com/api-doc/contract/account/Get-Single-Account",)),
        endpoint("futures_order_classic", group="trade", market="usdt_futures", title="Classic Futures Place Order", method="POST", path="/api/v2/mix/order/place-order", auth="trade", symbol_mode="product_type_and_symbol", response_symbol_field="symbol(request)", response_fields=("orderId", "clientOid"), price_types=(), intended_use="Выставление классического futures-ордера.", source_urls=("https://www.bitget.com/api-doc/contract/trade/Place-Order",)),
        endpoint("uta_order", group="trade", market="spot", title="UTA Place Order", method="POST", path="/api/v3/trade/place-order", auth="trade", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("orderId", "clientOid"), price_types=(), intended_use="Единый UTA order endpoint для spot/margin/futures.", source_urls=("https://www.bitget.com/api-doc/uta/intro", "https://www.bitget.com/api-doc/uta/trade/Place-Order")),
    ),
)
