from __future__ import annotations

from app.exchange_info_base.common import account_type, endpoint, market_type, price_types
from app.exchange_info_base.models import ExchangeReference

MEXC_REFERENCE = ExchangeReference(
    exchange_id="mexc",
    title="MEXC",
    verified_scope="Official MEXC Spot V3 and Contract V1 docs.",
    account_types=(
        account_type("spot", "Spot", "Spot account MEXC V3.", tradable_products=("spot",)),
        account_type("contract", "Contract", "Contract/futures account MEXC contract API.", tradable_products=("perpetual_contract",), notes=("В официальной contract V1 docs контракты описаны как SWAP/perpetual. Order endpoints помечены under maintenance, но path опубликован.",)),
    ),
    market_types=(
        market_type("spot", "Spot", native_categories=("SPOT",)),
        market_type("perpetual_contract", "Perpetual Contract", native_categories=("CONTRACT", "SWAP"), contract_types=("perpetual",), settlement_types=("USDT",)),
    ),
    price_types=price_types("last", "bid", "ask", "mid", "index", "fair", "open", "high", "low", "close"),
    endpoints=(
        endpoint("spot_exchange_info", group="market_data", market="spot", title="Spot Exchange Information", method="GET", path="/api/v3/exchangeInfo", auth="public", symbol_mode="bulk", response_symbol_field="symbols[].symbol", response_fields=("status", "baseAsset", "quoteAsset", "permissions"), price_types=(), intended_use="Universe spot instruments.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("spot_24hr_ticker", group="market_data", market="spot", title="Spot 24hr Ticker", method="GET", path="/api/v3/ticker/24hr", auth="public", symbol_mode="bulk_or_symbol", response_symbol_field="symbol", response_fields=("lastPrice", "quoteVolume"), price_types=("last",), intended_use="Spot last price и 24h volume.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("spot_book_ticker", group="market_data", market="spot", title="Spot Order Book Ticker", method="GET", path="/api/v3/ticker/bookTicker", auth="public", symbol_mode="bulk_or_symbol", response_symbol_field="symbol", response_fields=("bidPrice", "askPrice"), price_types=("bid", "ask", "mid"), intended_use="Best bid/ask по споту.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("spot_klines", group="market_data", market="spot", title="Spot Klines", method="GET", path="/api/v3/klines", auth="public", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Исторические spot OHLC.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("spot_account", group="account", market="spot", title="Spot Account Information", method="GET", path="/api/v3/account", auth="user_data", symbol_mode="none", response_symbol_field="balances[].asset", response_fields=("accountType", "balances", "permissions"), price_types=(), intended_use="Spot balances и permissions.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("spot_order", group="trade", market="spot", title="Spot New Order", method="POST", path="/api/v3/order", auth="trade", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("symbol", "orderId", "price", "origQty", "side", "type"), price_types=(), intended_use="Выставление spot-ордера.", source_urls=("https://mexcdevelop.github.io/apidocs/spot_v3_en/?shell=",)),
        endpoint("contract_detail", group="market_data", market="perpetual_contract", title="Get Contract Detail", method="GET", path="/api/v1/contract/detail", auth="public", symbol_mode="bulk_or_symbol", response_symbol_field="data[].symbol", response_fields=("symbol", "displayNameEn", "positionOpenType", "baseCoin", "quoteCoin", "settleCoin", "state", "apiAllowed"), price_types=(), intended_use="Universe perpetual contracts и metadata, включая apiAllowed.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_ticker", group="market_data", market="perpetual_contract", title="Get Contract Ticker", method="GET", path="/api/v1/contract/ticker", auth="public", symbol_mode="bulk_or_symbol", response_symbol_field="data[].symbol", response_fields=("lastPrice", "bid1", "ask1", "amount24", "volume24", "riseFallRate", "fairPrice", "indexPrice"), price_types=("last", "bid", "ask", "mid", "fair", "index"), intended_use="Bulk/single perpetual price snapshot.", notes=("Official docs называют этот route contract ticker/trend data block.",), source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_depth", group="market_data", market="perpetual_contract", title="Get Contract Depth", method="GET", path="/api/v1/contract/depth/{symbol}", auth="public", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("asks", "bids", "timestamp"), price_types=("bid", "ask"), intended_use="Стакан по контракту.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_index_price", group="market_data", market="perpetual_contract", title="Get Contract Index Price", method="GET", path="/api/v1/contract/index_price/{symbol}", auth="public", symbol_mode="symbol", response_symbol_field="data.symbol", response_fields=("indexPrice",), price_types=("index",), intended_use="Index price snapshot.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_fair_price", group="market_data", market="perpetual_contract", title="Get Contract Fair Price", method="GET", path="/api/v1/contract/fair_price/{symbol}", auth="public", symbol_mode="symbol", response_symbol_field="data.symbol", response_fields=("fairPrice",), price_types=("fair",), intended_use="Fair price snapshot.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_funding_rate", group="market_data", market="perpetual_contract", title="Get Contract Funding Rate", method="GET", path="/api/v1/contract/funding_rate/{symbol}", auth="public", symbol_mode="symbol", response_symbol_field="data.symbol", response_fields=("fundingRate", "collectCycle", "nextSettleTime"), price_types=(), intended_use="Funding rate, interval and next settlement time.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_kline", group="market_data", market="perpetual_contract", title="Get Contract Kline", method="GET", path="/api/v1/contract/kline/{symbol}", auth="public", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("open", "high", "low", "close"), price_types=("open", "high", "low", "close"), intended_use="Исторические contract OHLC.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_account_assets", group="account", market="perpetual_contract", title="Get All Informations of User's Asset", method="GET", path="/api/v1/private/account/assets", auth="user_data", symbol_mode="none", response_symbol_field="data[].currency", response_fields=("currency", "availableBalance", "positionMargin", "equity"), price_types=(), intended_use="Баланс contract account.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_positions", group="account", market="perpetual_contract", title="Get Current Holding Position", method="GET", path="/api/v1/private/position/open_positions", auth="user_data", symbol_mode="optional_symbol", response_symbol_field="data[].symbol", response_fields=("symbol", "positionType", "holdVol", "openAvgPrice"), price_types=(), intended_use="Текущие позиции contract account.", source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
        endpoint("contract_order_submit", group="trade", market="perpetual_contract", title="Contract Order Submit", method="POST", path="/api/v1/private/order/submit", auth="trade", symbol_mode="symbol", response_symbol_field="symbol(request)", response_fields=("data",), price_types=(), intended_use="Выставление contract order.", notes=("Official docs помечают route как Under maintenance, но endpoint и параметры опубликованы.",), source_urls=("https://mexcdevelop.github.io/apidocs/contract_v1_en/?python=",)),
    ),
)
